name: Send Kakao Notification

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: '학급 이름'
        required: true
        default: '2학년 7반'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run python script
        env:
          # 깃허브 Secrets에 저장한 카카오 API 키를 파이썬에게 전달합니다.
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
        run: |
          # main.py 파일을 실행하면서 사용자가 입력한 학급 이름을 같이 보냅니다.
          python main.py "${{ github.event.inputs.class_name }}"
